import './globals.css'
import NavBar from '../components/NavBar'
import Providers from './providers'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Providers>
          <NavBar />
        
          {children}
        </Providers>
      </body>
    </html>
  )
}
